export { default as StartScreen } from './StartScreen'
export { default as LoginScreen } from './AuthScreen/LoginScreen'
export { default as RegisterScreen } from './AuthScreen/RegisterScreen'
export { default as ResetPasswordScreen } from './AuthScreen/ResetPasswordScreen'
export { default as Dashboard } from './Dashboard'
export { default as FavoriteAnimalsScreen } from './AnimalScreen/FavoriteAnimalsScreen'
export { default as AnimalDetailsScreen } from './AnimalScreen/AnimalDetailsScreen'
